modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "entris"
version = "${version}"
displayName = "Entris"
authors = "Slainlight"
description = '''
More Exciting Enchanting
'''
logoFile = "icon.png"

[[dependencies.entris]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.entris]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,]"
ordering = "NONE"
side = "BOTH"

[[dependencies.entris]]
modId = "fabric_api"
mandatory = true
versionRange = "[0,)"
